#!/usr/bin/env bash

read -p "Please Enter the endpoint:" ENDPOINT
read -p "Please Enter the MLB Server IP address or FQDN :" SERVER
if [ -z "$ENDPOINT" ] || [ -z "$SERVER" ]
then
        echo "Please enter a valid endpoint/server"

else
        echo -e "\n-------------------------------------"
        echo -e "Please find the SSL Certificate expiration details\n"
        echo | openssl s_client -servername $ENDPOINT -connect $SERVER:443 2>/dev/null | openssl x509 -noout -dates
        echo -e "\n-------------------------------------"
fi
